# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
apiVersion: batch/v1 
kind: CronJob
metadata:
  name: newsletter
  namespace: cloudcomputing-app
spec:
  schedule: "* * * * 0"
  jobTemplate:
    spec:
      template:
        metadata:
          name: newsletter-job
          labels: 
            app: newsletter-job
        spec:
          containers:
          - name: newsletter
            image: flavrotary/online-shopping-newsletter:latest
            command: ["/bin/sh"]
            args: ["-c", "sleep 10; curl "]
            env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: shopping_db
          restartPolicy: OnFailure
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: newsletter-service
  namespace: cloudcomputing-app
spec:
  selector:
    app: newsletter-job
  type: ClusterIP
  ports:
  - name: myjob
    protocol: TCP
    port: 5001
    targetPort: 5000
---

