# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjobname
  namespace: cloudcomputing-app
spec:
  schedule: "* * * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: newsletter
            image: flavrotary/online-shopping-products:latest
            env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: passwords
            - name: MONGO_INITDB_DATABASE
              value: shopping_db
          restartPolicy: OnFailure
---
