# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  users-deployment
  namespace: cloudcomputing-app
  labels:
    app:  users-deployment
spec:
  selector:
    matchLabels:
      app: users-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: users-deployment
    spec:
      containers:
      - name:  users
        image:  flavrotary/online-shopping-user:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: password
          - name: MONGO_INITDB_DATABASE
            value: shopping_db
        ports:
        - containerPort:  5000
      restartPolicy: Always
---

# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: cloudcomputing-app
spec:
  selector:
    app: users-deployment
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5004
    targetPort: 5000
---

