# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo-deployment
  namespace: cloudcomputing-app
  labels:
    app:  mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mongo-deployment
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
          - containerPort: 27017
        args: ["--dbpath","/data/db"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
        - name: MONGO_INITDB_DATABASE
          value: shopping_db
        volumeMounts:
        - name: "mongo-data"
          mountPath: "/data/db"
      volumes:
      - name: "mongo-data"
        persistentVolumeClaim:
          claimName: "pvc"

---

# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: cloudcomputing-app
spec:
  selector:
    app: mongo-deployment
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    
---
