apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  namespace: cloudcomputing-app
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo