# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
  namespace: cloudcomputing-app
type: Opaque
data:
  password: cGFzc3dvcmQK
  username: cm9vdAo=
---
